package Vista;

import Report.EstadisticaAnualReport;
import Report.EstadisticaMensualReport;
import Report.EstadisticaTrimestralReport;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;

public class frmReportEstadistico extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmReportMensualSan
     */
    public frmReportEstadistico() {
        initComponents();
        this.cargarAnio();
        this.cargarMes();
        this.botones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnGenerarReporte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboAnio = new javax.swing.JComboBox<>();
        comboMes = new javax.swing.JComboBox<>();
        btnAnual = new javax.swing.JRadioButton();
        btnMensual = new javax.swing.JRadioButton();
        btnTrimestral = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("REPORTE ESTADÍSTICO");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        btnGenerarReporte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGenerarReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/analitica.png"))); // NOI18N
        btnGenerarReporte.setText("Generar Reporte");
        btnGenerarReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AÑO:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MES:");

        comboAnio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        comboMes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnAnual.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(btnAnual);
        btnAnual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAnual.setForeground(new java.awt.Color(255, 255, 255));
        btnAnual.setText("ANUAL");
        btnAnual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnualActionPerformed(evt);
            }
        });

        btnMensual.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(btnMensual);
        btnMensual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMensual.setForeground(new java.awt.Color(255, 255, 255));
        btnMensual.setSelected(true);
        btnMensual.setText("MENSUAL");
        btnMensual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMensualActionPerformed(evt);
            }
        });

        btnTrimestral.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(btnTrimestral);
        btnTrimestral.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTrimestral.setForeground(new java.awt.Color(255, 255, 255));
        btnTrimestral.setText("TRIMESTRAL");
        btnTrimestral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrimestral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrimestralActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboMes, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMensual)
                        .addGap(98, 98, 98)
                        .addComponent(btnTrimestral)
                        .addGap(11, 11, 11)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGenerarReporte, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAnual, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(comboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnGenerarReporte)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMensual)
                    .addComponent(btnTrimestral)
                    .addComponent(btnAnual))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        this.generarReporte();
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    private void btnAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnualActionPerformed
        this.comboAnio.setEnabled(true);
        this.comboMes.setEnabled(false);
        this.comboMes.removeAllItems();
    }//GEN-LAST:event_btnAnualActionPerformed

    private void btnMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensualActionPerformed
        this.comboAnio.setEnabled(true);
        this.comboMes.setEnabled(true);
        this.cargarMes();
    }//GEN-LAST:event_btnMensualActionPerformed

    private void btnTrimestralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrimestralActionPerformed
        this.comboAnio.setEnabled(true);
        this.comboMes.setEnabled(true);
        this.cargarMes();
    }//GEN-LAST:event_btnTrimestralActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAnual;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JRadioButton btnMensual;
    private javax.swing.JRadioButton btnTrimestral;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Integer> comboAnio;
    private javax.swing.JComboBox<String> comboMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void cargarAnio() {
        Calendar calendar = Calendar.getInstance();
        int year = calendar.get(Calendar.YEAR);

        DefaultComboBoxModel<Integer> yearModel = new DefaultComboBoxModel<>();
        for (int i = year; i >= 2015; i--) {
            yearModel.addElement(i);
        }

        this.comboAnio.setModel(yearModel);
        this.comboAnio.setSelectedItem(year);
    }

    private void cargarMes() {
        Calendar calendar = Calendar.getInstance();
        int month = calendar.get(Calendar.MONTH);

        DefaultComboBoxModel<String> monthModel = new DefaultComboBoxModel<>();
        String[] months = new String[]{"ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO",
            "AGOSTO", "SETIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE"};
        for (int i = 0; i < months.length; i++) {
            monthModel.addElement(months[i]);
        }

        this.comboMes.setModel(monthModel);
        this.comboMes.setSelectedItem(month);
    }

    private void botones() {
        this.btnGenerarReporte.setOpaque(false);
        this.btnGenerarReporte.setContentAreaFilled(false);
        this.btnGenerarReporte.setBorderPainted(false);
        this.btnGenerarReporte.setToolTipText("Generar Reporte");
    }

    private void generarReporte() {
        int anio = (Integer) this.comboAnio.getSelectedItem();
        try {
            if (this.btnMensual.isSelected()) {
                int mes = this.comboMes.getSelectedIndex() + 1;
                EstadisticaMensualReport report = new EstadisticaMensualReport();
                report.verReporte(mes, anio);
            }
            if (this.btnTrimestral.isSelected()) {
                int mes = this.comboMes.getSelectedIndex() + 1;
                EstadisticaTrimestralReport report = new EstadisticaTrimestralReport();
                report.verReporte(mes, anio);
            }
            if (this.btnAnual.isSelected()) {
                EstadisticaAnualReport report = new EstadisticaAnualReport();
                report.verReporte(anio);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}
